server:
  port: 10000
spring:
  application:
    name: member-service-provider-10000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.juzi.springcloud.model.entity
