server:
  port: 80

spring:
  application:
    name: member-service-consumer-openfegin-80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 全部采集
      probability: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka
logging:
  level:
    # 自定义日志级别配置
    com.juzi.springcloud.service.MemberFeignService: debug